'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("165, 0, 130")>  _
        Public ReadOnly Property LabelColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("LabelColor"),Global.System.Drawing.Color)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("235, 183, 63")>  _
        Public ReadOnly Property ButtonColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ButtonColor"),Global.System.Drawing.Color)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 11.25pt, style=Bold")>  _
        Public ReadOnly Property ButtonFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("ButtonFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 10pt")>  _
        Public ReadOnly Property EditFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("EditFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 11.25pt, style=Bold")>  _
        Public ReadOnly Property LabelFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("LabelFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 10pt")>  _
        Public ReadOnly Property MenuButtonFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("MenuButtonFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("235, 183, 63")>  _
        Public ReadOnly Property MenuButtonColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuButtonColor"),Global.System.Drawing.Color)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("165, 0, 130")>  _
        Public ReadOnly Property MenuBarColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuBarColor"),Global.System.Drawing.Color)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 16pt")>  _
        Public ReadOnly Property MenuBarFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("MenuBarFont"),Global.System.Drawing.Font)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("198, 0, 156")>  _
        Public ReadOnly Property MenuBarColor_Select() As Global.System.Drawing.Color
            Get
                Return CType(Me("MenuBarColor_Select"),Global.System.Drawing.Color)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LoginUserSave() As Boolean
            Get
                Return CType(Me("LoginUserSave"),Boolean)
            End Get
            Set
                Me("LoginUserSave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LoginUser() As String
            Get
                Return CType(Me("LoginUser"),String)
            End Get
            Set
                Me("LoginUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Postal\KEN_ALL.csv")>  _
        Public Property Postal() As String
            Get
                Return CType(Me("Postal"),String)
            End Get
            Set
                Me("Postal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("〇左のQRコードからマイページにアクセスし、検体IDの登録を行ってください。")>  _
        Public Property SCREEN_IRAISHO_HAKKO_COMMENT1() As String
            Get
                Return CType(Me("SCREEN_IRAISHO_HAKKO_COMMENT1"),String)
            End Get
            Set
                Me("SCREEN_IRAISHO_HAKKO_COMMENT1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("〇検体ID登録後、希望される検査項目・問診について回答をお願いいたします。")>  _
        Public Property SCREEN_IRAISHO_HAKKO_COMMENT2() As String
            Get
                Return CType(Me("SCREEN_IRAISHO_HAKKO_COMMENT2"),String)
            End Get
            Set
                Me("SCREEN_IRAISHO_HAKKO_COMMENT2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastImportOkuriPath() As String
            Get
                Return CType(Me("LastImportOkuriPath"),String)
            End Get
            Set
                Me("LastImportOkuriPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastOkuriType() As Integer
            Get
                Return CType(Me("LastOkuriType"),Integer)
            End Get
            Set
                Me("LastOkuriType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastShukaSearchCSVFileName() As String
            Get
                Return CType(Me("LastShukaSearchCSVFileName"),String)
            End Get
            Set
                Me("LastShukaSearchCSVFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastOkurijoBangoHanneiCSVFileName() As String
            Get
                Return CType(Me("LastOkurijoBangoHanneiCSVFileName"),String)
            End Get
            Set
                Me("LastOkurijoBangoHanneiCSVFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastImportJukenshaPath() As String
            Get
                Return CType(Me("LastImportJukenshaPath"),String)
            End Get
            Set
                Me("LastImportJukenshaPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastUriageRenkeiCSVFileName() As String
            Get
                Return CType(Me("LastUriageRenkeiCSVFileName"),String)
            End Get
            Set
                Me("LastUriageRenkeiCSVFileName") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.ATDS.Win.App.My.MySettings
            Get
                Return Global.ATDS.Win.App.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
