'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ATDS.Win.App.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.well-mill.com/version-test/.
        '''</summary>
        Friend ReadOnly Property EC_URL() As String
            Get
                Return ResourceManager.GetString("EC_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d11c248b3cb1f60b46a1928458a3caf5.
        '''</summary>
        Friend ReadOnly Property ECSiteAPIKey() As String
            Get
                Return ResourceManager.GetString("ECSiteAPIKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.well-mill.com/version-test.
        '''</summary>
        Friend ReadOnly Property ECSiteAPIUrl() As String
            Get
                Return ResourceManager.GetString("ECSiteAPIUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /api/1.1/wf/create_new_result.
        '''</summary>
        Friend ReadOnly Property ECSiteKekkaHokokuURL() As String
            Get
                Return ResourceManager.GetString("ECSiteKekkaHokokuURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /api/1.1/wf/update_fulfillment.
        '''</summary>
        Friend ReadOnly Property ECSiteShohinHasoURL() As String
            Get
                Return ResourceManager.GetString("ECSiteShohinHasoURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVファイルのデータが正しくない.
        '''</summary>
        Friend ReadOnly Property ERR_CSVDataItems() As String
            Get
                Return ResourceManager.GetString("ERR_CSVDataItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVの形式が正しくありません。.
        '''</summary>
        Friend ReadOnly Property ERR_CSVFormat() As String
            Get
                Return ResourceManager.GetString("ERR_CSVFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVのインポートが失敗しました。.
        '''</summary>
        Friend ReadOnly Property ERR_CSVImport() As String
            Get
                Return ResourceManager.GetString("ERR_CSVImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSVファイルにデータがありません。.
        '''</summary>
        Friend ReadOnly Property ERR_CSVNoData() As String
            Get
                Return ResourceManager.GetString("ERR_CSVNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to メールの形式が正しくありません。.
        '''</summary>
        Friend ReadOnly Property ERR_EmailFormat() As String
            Get
                Return ResourceManager.GetString("ERR_EmailFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}の終了日は、開始日以降の日付を入力してください。.
        '''</summary>
        Friend ReadOnly Property ERR_EndDateAfterStartDate() As String
            Get
                Return ResourceManager.GetString("ERR_EndDateAfterStartDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}Toには{1}Fromより大きい値を入力してください。.
        '''</summary>
        Friend ReadOnly Property ERR_EndValueAfterStartValue() As String
            Get
                Return ResourceManager.GetString("ERR_EndValueAfterStartValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}は本日以降の日付を入力してください。.
        '''</summary>
        Friend ReadOnly Property ERR_EnterDateAfterToday() As String
            Get
                Return ResourceManager.GetString("ERR_EnterDateAfterToday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}が既に存在しています。.
        '''</summary>
        Friend ReadOnly Property ERR_ExistedError() As String
            Get
                Return ResourceManager.GetString("ERR_ExistedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ファイルが見つかりません。.
        '''</summary>
        Friend ReadOnly Property ERR_FileNotFound() As String
            Get
                Return ResourceManager.GetString("ERR_FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}情報の登録が出来ませんでした。.
        '''</summary>
        Friend ReadOnly Property ERR_InsertError() As String
            Get
                Return ResourceManager.GetString("ERR_InsertError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 生年月日は1900/01/01から現在の日付まで入力してください。.
        '''</summary>
        Friend ReadOnly Property ERR_InvalidBirthday() As String
            Get
                Return ResourceManager.GetString("ERR_InvalidBirthday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 注文情報が存在します。最終取引日：{0}.
        '''</summary>
        Friend ReadOnly Property ERR_InvalidTorihikiChushi() As String
            Get
                Return ResourceManager.GetString("ERR_InvalidTorihikiChushi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検体IDのバーコードではありません（形式不一致）.
        '''</summary>
        Friend ReadOnly Property ERR_KentaiIDFormat() As String
            Get
                Return ResourceManager.GetString("ERR_KentaiIDFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検体IDのバーコードではありません（桁数不一致）.
        '''</summary>
        Friend ReadOnly Property ERR_KentaiIDLenght() As String
            Get
                Return ResourceManager.GetString("ERR_KentaiIDLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}にマイナスの値が入力されています。.
        '''</summary>
        Friend ReadOnly Property ERR_MinusCheck() As String
            Get
                Return ResourceManager.GetString("ERR_MinusCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ヤマトB2・ゆうプリRが混在しています。再度確認してください。.
        '''</summary>
        Friend ReadOnly Property ERR_MixedOkuriType() As String
            Get
                Return ResourceManager.GetString("ERR_MixedOkuriType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 該当するデータがありません。.
        '''</summary>
        Friend ReadOnly Property ERR_NoData() As String
            Get
                Return ResourceManager.GetString("ERR_NoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 対象のデータが存在しません。.
        '''</summary>
        Friend ReadOnly Property ERR_NotExist() As String
            Get
                Return ResourceManager.GetString("ERR_NotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}は有効な値が指定されていません。.
        '''</summary>
        Friend ReadOnly Property ERR_NotVaildValue() As String
            Get
                Return ResourceManager.GetString("ERR_NotVaildValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文情報が存在します。最終取引日：{0}。.
        '''</summary>
        Friend ReadOnly Property ERR_OrderExistAfterStopTradingDate() As String
            Get
                Return ResourceManager.GetString("ERR_OrderExistAfterStopTradingDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力した郵便番号は存在しません。.
        '''</summary>
        Friend ReadOnly Property ERR_PostCodeNotExist() As String
            Get
                Return ResourceManager.GetString("ERR_PostCodeNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}を入力してください。.
        '''</summary>
        Friend ReadOnly Property ERR_PromptForEntry() As String
            Get
                Return ResourceManager.GetString("ERR_PromptForEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 名称区分は[対象の区分名]を設定してください。.
        '''</summary>
        Friend ReadOnly Property ERR_PromptForKubunEntry() As String
            Get
                Return ResourceManager.GetString("ERR_PromptForKubunEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}は必須項目です。.
        '''</summary>
        Friend ReadOnly Property ERR_RequiredCheck() As String
            Get
                Return ResourceManager.GetString("ERR_RequiredCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 明細情報へ1件以上の情報を追加してください。.
        '''</summary>
        Friend ReadOnly Property ERR_ShukaDetailsRequired() As String
            Get
                Return ResourceManager.GetString("ERR_ShukaDetailsRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ステータスは待機のみ登録可。.
        '''</summary>
        Friend ReadOnly Property ERR_StatusOnlyStandby() As String
            Get
                Return ResourceManager.GetString("ERR_StatusOnlyStandby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to インポートファイル内のデータでマッピング位置を設定してください。.
        '''</summary>
        Friend ReadOnly Property ERR_TorikomiPositionNoMapping() As String
            Get
                Return ResourceManager.GetString("ERR_TorikomiPositionNoMapping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 験者情報取込ファイル項目位置のデータが存在しません.
        '''</summary>
        Friend ReadOnly Property ERR_TorikomiPositionNotExist() As String
            Get
                Return ResourceManager.GetString("ERR_TorikomiPositionNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}情報の更新が出来ませんでした。.
        '''</summary>
        Friend ReadOnly Property ERR_UpdateError() As String
            Get
                Return ResourceManager.GetString("ERR_UpdateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}ゼロは登録しない。.
        '''</summary>
        Friend ReadOnly Property ERR_ZeroCheck() As String
            Get
                Return ResourceManager.GetString("ERR_ZeroCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 単価ゼロは登録しない。.
        '''</summary>
        Friend ReadOnly Property ERR_ZeroTanka() As String
            Get
                Return ResourceManager.GetString("ERR_ZeroTanka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://well-mill.com/version-test/sample-registration?sample={0}.
        '''</summary>
        Friend ReadOnly Property IRAISHO_HAKKO_QR_URL() As String
            Get
                Return ResourceManager.GetString("IRAISHO_HAKKO_QR_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 住所へ反映してもよろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_ChangeAddressConfrim() As String
            Get
                Return ResourceManager.GetString("MSG_ChangeAddressConfrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内容が変更されていますが、クリアしてよろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_ClearConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_ClearConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内容が変更されていますが、終了してよろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_CloseConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_CloseConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 削除が完了しました。.
        '''</summary>
        Friend ReadOnly Property MSG_DeleteCompleted() As String
            Get
                Return ResourceManager.GetString("MSG_DeleteCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 削除します。よろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_DeleteConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_DeleteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 選択中の行を削除します。よろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_DeleteRowConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_DeleteRowConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 内容が変更されていますが、終了してよろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_EndConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_EndConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入数で割り切れない本数が入力されています。.
        '''</summary>
        Friend ReadOnly Property MSG_IrisuConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_IrisuConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 出力が完了しました。.
        '''</summary>
        Friend ReadOnly Property MSG_OutputFinished() As String
            Get
                Return ResourceManager.GetString("MSG_OutputFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 登録が完了しました。.
        '''</summary>
        Friend ReadOnly Property MSG_RegistrationCompleted() As String
            Get
                Return ResourceManager.GetString("MSG_RegistrationCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 登録します。よろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_RegistrationConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_RegistrationConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ESCサイトへ連携するとき、以下のエラーが発生しました。{0}.
        '''</summary>
        Friend ReadOnly Property MSG_ShohinHasoError() As String
            Get
                Return ResourceManager.GetString("MSG_ShohinHasoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 帳票が出ます。よろしいですか？.
        '''</summary>
        Friend ReadOnly Property MSG_ShowReportConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_ShowReportConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新が完了しました。.
        '''</summary>
        Friend ReadOnly Property MSG_UpdateCompleted() As String
            Get
                Return ResourceManager.GetString("MSG_UpdateCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to エラーの検体IDが存在しています。確定を実施しますか？.
        '''</summary>
        Friend ReadOnly Property MSG_UpdateKentaiUketsukeConfirm() As String
            Get
                Return ResourceManager.GetString("MSG_UpdateKentaiUketsukeConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(([^&lt;&gt;()\[\]\\.,;:\s@&quot;]+(\.[^&lt;&gt;()\[\]\\.,;:\s@&quot;]+)*)|(&quot;.+&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$.
        '''</summary>
        Friend ReadOnly Property REGEX_EmailFormat() As String
            Get
                Return ResourceManager.GetString("REGEX_EmailFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Renkei() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Renkei", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 確認.
        '''</summary>
        Friend ReadOnly Property UI_Confirmation() As String
            Get
                Return ResourceManager.GetString("UI_Confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to エラー.
        '''</summary>
        Friend ReadOnly Property UI_Error() As String
            Get
                Return ResourceManager.GetString("UI_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 女性.
        '''</summary>
        Friend ReadOnly Property UI_Female() As String
            Get
                Return ResourceManager.GetString("UI_Female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 情報.
        '''</summary>
        Friend ReadOnly Property UI_Information() As String
            Get
                Return ResourceManager.GetString("UI_Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 男性.
        '''</summary>
        Friend ReadOnly Property UI_Male() As String
            Get
                Return ResourceManager.GetString("UI_Male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to なし.
        '''</summary>
        Friend ReadOnly Property UI_No() As String
            Get
                Return ResourceManager.GetString("UI_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未回答.
        '''</summary>
        Friend ReadOnly Property UI_SexNoAnswered() As String
            Get
                Return ResourceManager.GetString("UI_SexNoAnswered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to あり.
        '''</summary>
        Friend ReadOnly Property UI_Yes() As String
            Get
                Return ResourceManager.GetString("UI_Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yoko() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yoko", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
