Option Strict Off
Option Explicit On
Public Module basMessage
    '******************************************************************************
    ' ﾌﾟﾛｼﾞｪｸﾄ名  : ＭＫシステム共通
    ' ファイル名  : Message.bas
    ' 内    容    : システム共通メッセージ
    ' 備    考    :
    ' 関数一覧    : <Public>
    '               <Private>
    '
    ' 変更履歴  :
    '   Version     日  付      氏  名             修正内容
    '   -----------+-----------+------------------+--------------------------------
    '   02.00.00    2007/09/21  廣井  芳明         新規作成
    '
    '******************************************************************************
    '==============================================================================
    ' メッセージタイトル
    '==============================================================================
    Public Const GC_ERR_TITLE As String = "警告"
    Public Const GC_QST_TITLE As String = "確認"
    Public Const GC_QST_REF_TITLE As String = "反映確認"
    Public Const GC_QST_PNT_TITLE As String = "印刷確認"
    Public Const GC_QST_RGS_TITLE As String = "登録確認"
    Public Const GC_QST_RUN_TITLE As String = "実行確認"
    Public Const GC_QST_DEL_TITLE As String = "削除確認"
    Public Const GC_QST_IPT_TITLE As String = "入力確認"
    Public Const GC_SUC_TITLE As String = "正常終了"

    '==============================================================================
    ' 通常メッセージ
    '==============================================================================
    Public Const GC_SUC_MSG_0001 As String = "処理は正常に終了しました。"
    Public Const GC_SUC_MSG_0002 As String = "データの取込が完了しましたが，" & vbCrLf & "エラーがあるレコードが存在します。"

    '==============================================================================
    ' エラーメッセージ
    '==============================================================================
    '----------------------------------
    ' データ存在チェック
    '----------------------------------
    Public Const GC_ERR_MSG_0001 As String = "得意先マスタが未登録です。"
    Public Const GC_ERR_MSG_0002 As String = "運管給与マスタが未登録です。"
    Public Const GC_ERR_MSG_0003 As String = "従業員マスタが未登録です。"
    Public Const GC_ERR_MSG_0004 As String = "運管勤怠マスタが未登録です。"
    Public Const GC_ERR_MSG_0005 As String = "契約マスタが未登録です。"
    Public Const GC_ERR_MSG_0006 As String = "銀行マスタが未登録です。"
    Public Const GC_ERR_MSG_0007 As String = "支店マスタが未登録です。"
    Public Const GC_ERR_MSG_0008 As String = "口座番号マスタが未登録です。"
    Public Const GC_ERR_MSG_0009 As String = "商品マスタが未登録です。"
    Public Const GC_ERR_MSG_0010 As String = "契約マスタが未登録です。"
    Public Const GC_ERR_MSG_0011 As String = "契約形態マスタが未登録です。"
    Public Const GC_ERR_MSG_0012 As String = "郵便番号マスタが未登録です。"
    Public Const GC_ERR_MSG_0013 As String = "コントロールマスタが未登録です。"
    Public Const GC_ERR_MSG_0014 As String = "部署マスタが未登録です。"
    Public Const GC_ERR_MSG_0015 As String = "会社マスタが未登録です。"
    Public Const GC_ERR_MSG_0016 As String = "扱業者マスタが未登録です。"
    Public Const GC_ERR_MSG_0017 As String = "権限設定テーブルが未登録です。"
    Public Const GC_ERR_MSG_0018 As String = "既に登録されている得意先コードです。"
    Public Const GC_ERR_MSG_0019 As String = "既に退職されている従業員コードです。"
    Public Const GC_ERR_MSG_0020 As String = "既に処理済みです。"
    Public Const GC_ERR_MSG_0021 As String = "度処理済みです。"
    Public Const GC_ERR_MSG_0022 As String = "処理対象のデータが存在しません。"
    Public Const GC_ERR_MSG_0023 As String = "楽々道中との連携で, 既に使用されている売上番号です。"
    Public Const GC_ERR_MSG_0024 As String = "売掛データが存在するため,削除できません。"
    Public Const GC_ERR_MSG_0025 As String = "シフトマスタが未登録です。"
    Public Const GC_ERR_MSG_0026 As String = "規定公休日数マスタが未登録です。"
    Public Const GC_ERR_MSG_0027 As String = "勤怠マスタが未登録です。"
    Public Const GC_ERR_MSG_0028 As String = "税率マスタが未登録です。"
    Public Const GC_ERR_MSG_0029 As String = "営業車輌マスタが未登録です。"
    Public Const GC_ERR_MSG_0030 As String = "ＭＫ会員マスタが未登録です。"
    Public Const GC_ERR_MSG_0031 As String = "既に解約されている会員コードです。"
    Public Const GC_ERR_MSG_0032 As String = "カレンダマスタが未登録です。"
    Public Const GC_ERR_MSG_0033 As String = "車輌区分マスタが未登録です。"
    Public Const GC_ERR_MSG_0034 As String = "名称マスタが未登録です。"
    Public Const GC_ERR_MSG_0035 As String = "パーフェクトテーブルが未登録です。"
    Public Const GC_ERR_MSG_0036 As String = "既に使用されているパーフェクト番号です。"
    Public Const GC_ERR_MSG_0037 As String = "空きのパーフェクト番号がありません。"
    Public Const GC_ERR_MSG_0038 As String = "車種マスタが未登録です。"
    Public Const GC_ERR_MSG_0039 As String = "入力されたパーフェクト番号は, 現在未使用です。"
    Public Const GC_ERR_MSG_0040 As String = "既に登録済みです。"
    Public Const GC_ERR_MSG_0041 As String = "締日管理マスタが未登録です。"
    Public Const GC_ERR_MSG_0042 As String = "ＭＫカードマスタが未登録です。"
    Public Const GC_ERR_MSG_0043 As String = "未収区分マスタが未登録です。"
    Public Const GC_ERR_MSG_0044 As String = "整理番号が未登録または不正です。"
    Public Const GC_ERR_MSG_0045 As String = "給与計算済年月が未登録です。"
    Public Const GC_ERR_MSG_0046 As String = "入力された回数がPOS明細に存在しません。"
    Public Const GC_ERR_MSG_0047 As String = "入力された回数は既に使用されています。"
    Public Const GC_ERR_MSG_0048 As String = "入力された整理番号は受注データに存在しません。"
    Public Const GC_ERR_MSG_0049 As String = "入力された整理番号はチケット発行データに存在しません。"
    Public Const GC_ERR_MSG_0050 As String = "入力された回数は貸切明細に存在しません。"
    Public Const GC_ERR_MSG_0051 As String = "講義マスタが未登録です。"
    Public Const GC_ERR_MSG_0052 As String = "既に登録されている従業員コードです。"
    Public Const GC_ERR_MSG_0053 As String = "貸付入金テーブルにデータが存在するため, 削除できません。"
    Public Const GC_ERR_MSG_0054 As String = "週間スケジュールテーブルが未登録です。"
    Public Const GC_ERR_MSG_0055 As String = "スケジュールテーブルが未登録です。"
    Public Const GC_ERR_MSG_0056 As String = "有給休暇処理ステータスを取得できません。"
    Public Const GC_ERR_MSG_0057 As String = "入力された番号は予約一覧に存在しません。"
    Public Const GC_ERR_MSG_0058 As String = "勤務予定テーブルが未登録です。"
    Public Const GC_ERR_MSG_0059 As String = "勤務予定テーブルが未登録です。"
    Public Const GC_ERR_MSG_0060 As String = "同じキー項目のデータが存在するため, 処理できません。"
    Public Const GC_ERR_MSG_0061 As String = "ＰＯＳ設定テーブルが未登録です。"
    Public Const GC_ERR_MSG_0062 As String = "経費控除マスタが未登録です。"
    Public Const GC_ERR_MSG_0063 As String = "整理番号が未登録または不正です。"
    Public Const GC_ERR_MSG_0064 As String = "アルバイト従業員マスタが未登録です。"
    Public Const GC_ERR_MSG_0065 As String = "指定されたファイル名は既に存在します。"

    '----------------------------------
    ' 起動・パラメタチェック
    '----------------------------------
    Public Const GC_ERR_MSG_0100 As String = "起動するための引数が不足しています。"
    Public Const GC_ERR_MSG_0101 As String = "起動するための引数が超過しています。"
    Public Const GC_ERR_MSG_0102 As String = "の起動に失敗しました。"

    '----------------------------------
    ' 画面項目入力チェック（コード・区分）
    '----------------------------------
    Public Const GC_ERR_MSG_1000 As String = "会社コードを入力してください。"
    Public Const GC_ERR_MSG_1001 As String = "所属コードを入力してください。"
    Public Const GC_ERR_MSG_1002 As String = "車輌区分を入力してください。"
    Public Const GC_ERR_MSG_1003 As String = "シフト区分を入力してください。"
    Public Const GC_ERR_MSG_1004 As String = "車輌番号地区コードを入力してください。"
    Public Const GC_ERR_MSG_1005 As String = "車輌番号を入力してください。"
    Public Const GC_ERR_MSG_1006 As String = "無線番号を入力してください。"
    Public Const GC_ERR_MSG_1007 As String = "整理番号を入力してください。"
    Public Const GC_ERR_MSG_1008 As String = "従業員コードを入力してください。"
    Public Const GC_ERR_MSG_1009 As String = "勤怠コードを入力してください。"
    Public Const GC_ERR_MSG_1010 As String = "契約形態を入力してください。"
    Public Const GC_ERR_MSG_1011 As String = "得意先コードを入力してください。"
    Public Const GC_ERR_MSG_1012 As String = "銀行コードを入力してください。"
    Public Const GC_ERR_MSG_1013 As String = "支店コードを入力してください。"
    Public Const GC_ERR_MSG_1014 As String = "口座種別を入力してください。"
    Public Const GC_ERR_MSG_1015 As String = "口座番号を入力してください。"
    Public Const GC_ERR_MSG_1016 As String = "契約番号を入力してください。"
    Public Const GC_ERR_MSG_1017 As String = "検索条件を入力してください。"
    Public Const GC_ERR_MSG_1018 As String = "クーポン区分を入力してください。"
    Public Const GC_ERR_MSG_1019 As String = "得意先会社コードを入力してください。"
    Public Const GC_ERR_MSG_1020 As String = "得意先部門コードを入力してください。"
    Public Const GC_ERR_MSG_1021 As String = "運管得意先区分を入力してください。"
    Public Const GC_ERR_MSG_1022 As String = "商品コードを入力してください。"
    Public Const GC_ERR_MSG_1023 As String = "顧客区分を入力してください。"
    Public Const GC_ERR_MSG_1024 As String = "回収サイクルを入力してください。"
    Public Const GC_ERR_MSG_1025 As String = "請求書様式区分を入力してください。"
    Public Const GC_ERR_MSG_1026 As String = "請求先区分を入力してください。"
    Public Const GC_ERR_MSG_1027 As String = "税通知を入力してください。"
    Public Const GC_ERR_MSG_1028 As String = "税端数を入力してください。"
    Public Const GC_ERR_MSG_1029 As String = "振込先を入力してください。"
    Public Const GC_ERR_MSG_1030 As String = "請求会社コードを入力してください。"
    Public Const GC_ERR_MSG_1031 As String = "開始端数区分を入力してください。"
    Public Const GC_ERR_MSG_1032 As String = "終了端数区分を入力してください。"
    Public Const GC_ERR_MSG_1033 As String = "稼動端数区分を入力してください。"
    Public Const GC_ERR_MSG_1034 As String = "食事手当区分を入力してください。"
    Public Const GC_ERR_MSG_1035 As String = "宿泊手当区分を入力してください。"
    Public Const GC_ERR_MSG_1036 As String = "売上区分を入力してください。"
    Public Const GC_ERR_MSG_1037 As String = "勤務種別を入力してください。"
    Public Const GC_ERR_MSG_1038 As String = "報告書区分を入力してください。"
    Public Const GC_ERR_MSG_1039 As String = "部門コード１を入力してください。"
    Public Const GC_ERR_MSG_1040 As String = "部門コード２を入力してください。"
    Public Const GC_ERR_MSG_1041 As String = "部門コード３を入力してください。"
    Public Const GC_ERR_MSG_1042 As String = "種類を入力してください。"
    Public Const GC_ERR_MSG_1043 As String = "状況を入力してください。"
    Public Const GC_ERR_MSG_1044 As String = "病院コードを入力してください。"
    Public Const GC_ERR_MSG_1045 As String = "保険会社コードを入力してください。"
    Public Const GC_ERR_MSG_1046 As String = "種類コードを入力してください。"
    Public Const GC_ERR_MSG_1047 As String = "状況コードを入力してください。"
    Public Const GC_ERR_MSG_1048 As String = "詳細状況コードを入力してください。"
    Public Const GC_ERR_MSG_1049 As String = "賞与区分を入力してください。"
    Public Const GC_ERR_MSG_1050 As String = "システム区分を入力してください。"
    Public Const GC_ERR_MSG_1051 As String = "車種コードを入力してください。"
    Public Const GC_ERR_MSG_1052 As String = "未収区分を入力してください。"
    Public Const GC_ERR_MSG_1053 As String = "区分を入力してください。"
    Public Const GC_ERR_MSG_1054 As String = "入社区分を入力してください。"
    Public Const GC_ERR_MSG_1055 As String = "特別手当区分を入力してください。"
    Public Const GC_ERR_MSG_1056 As String = "本務代務区分を入力してください。"
    Public Const GC_ERR_MSG_1057 As String = "本務車輌区分を入力してください。"
    Public Const GC_ERR_MSG_1058 As String = "ファーストを入力してください。"
    Public Const GC_ERR_MSG_1059 As String = "免許証番号を入力してください。"
    Public Const GC_ERR_MSG_1060 As String = "コードを入力してください。"
    Public Const GC_ERR_MSG_1061 As String = "未収コードを入力してください。"
    Public Const GC_ERR_MSG_1062 As String = "パーフェクト番号を入力してください。"
    Public Const GC_ERR_MSG_1063 As String = "コードの入力形式が不正です。"
    Public Const GC_ERR_MSG_1064 As String = "会員コードを入力してください。"
    Public Const GC_ERR_MSG_1065 As String = "入金区分を入力してください。"
    Public Const GC_ERR_MSG_1066 As String = "管理コードを入力してください。"
    Public Const GC_ERR_MSG_1067 As String = "チケット還付有無区分を入力してください。"
    Public Const GC_ERR_MSG_1068 As String = "燃料区分を入力してください。"
    Public Const GC_ERR_MSG_1069 As String = "行先コードを入力してください。"
    Public Const GC_ERR_MSG_1070 As String = "用途区分を入力してください。"
    Public Const GC_ERR_MSG_1071 As String = "サイズ区分を入力してください。"
    Public Const GC_ERR_MSG_1072 As String = "印刷条件を入力してください。"
    Public Const GC_ERR_MSG_1073 As String = "明細区分を入力してください。"
    Public Const GC_ERR_MSG_1074 As String = "集計区分を入力してください。"
    Public Const GC_ERR_MSG_1075 As String = "タクシーハイヤー区分を入力してください。"
    Public Const GC_ERR_MSG_1076 As String = "勤務区分を入力してください。"
    Public Const GC_ERR_MSG_1077 As String = "勤次郎部門コードを入力してください。"
    Public Const GC_ERR_MSG_1078 As String = "ハイヤタクシ区分を入力してください。"
    Public Const GC_ERR_MSG_1079 As String = "利用区分を入力してください。"
    Public Const GC_ERR_MSG_1080 As String = "請求書発行区分を入力してください。"
    Public Const GC_ERR_MSG_1081 As String = "合計請求書有無を入力してください。"
    Public Const GC_ERR_MSG_1082 As String = "支払区分を入力してください。"
    Public Const GC_ERR_MSG_1083 As String = "入金種別を入力してください。"
    Public Const GC_ERR_MSG_1084 As String = "貸付項目コードを入力してください。"
    Public Const GC_ERR_MSG_1085 As String = "仮コード区分を入力してください。"
    Public Const GC_ERR_MSG_1086 As String = "講義コードを入力してください。"
    Public Const GC_ERR_MSG_1087 As String = "曜日を入力してください。"
    Public Const GC_ERR_MSG_1088 As String = "全集区分を入力してください。"
    Public Const GC_ERR_MSG_1089 As String = "検定区分を入力してください。"
    Public Const GC_ERR_MSG_1090 As String = "退職コードを入力してください。"
    Public Const GC_ERR_MSG_1091 As String = "指導場所コードを入力してください。"
    Public Const GC_ERR_MSG_1092 As String = "指導者コードを入力してください。"
    Public Const GC_ERR_MSG_1093 As String = "会員枝コードを入力してください。"

    '----------------------------------
    ' 画面項目入力チェック（日付・時刻）
    '----------------------------------
    Public Const GC_ERR_MSG_1100 As String = "営業日を入力してください。"
    Public Const GC_ERR_MSG_1101 As String = "営業日（自）を入力してください。"
    Public Const GC_ERR_MSG_1102 As String = "営業日（至）を入力してください。"
    Public Const GC_ERR_MSG_1103 As String = "日付を入力してください。"
    Public Const GC_ERR_MSG_1104 As String = "日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1105 As String = "日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1106 As String = "年月度を入力してください。"
    Public Const GC_ERR_MSG_1107 As String = "時間を入力してください。"
    Public Const GC_ERR_MSG_1108 As String = "日数を入力してください。"
    Public Const GC_ERR_MSG_1109 As String = "速度を入力してください。"
    Public Const GC_ERR_MSG_1110 As String = "請求締日を入力してください。"
    Public Const GC_ERR_MSG_1111 As String = "登録日を入力してください。"
    Public Const GC_ERR_MSG_1112 As String = "年度を入力してください。"
    Public Const GC_ERR_MSG_1113 As String = "入金日付を入力してください。"
    Public Const GC_ERR_MSG_1114 As String = "売上日付を入力してください。"
    Public Const GC_ERR_MSG_1115 As String = "契約日付を入力してください。"
    Public Const GC_ERR_MSG_1116 As String = "契約日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1117 As String = "契約日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1118 As String = "回収日を入力してください。"
    Public Const GC_ERR_MSG_1119 As String = "集計日付を入力してください。"
    Public Const GC_ERR_MSG_1120 As String = "日付(年月日)を入力してください。"
    Public Const GC_ERR_MSG_1121 As String = "日付(年月)を入力してください。"
    Public Const GC_ERR_MSG_1122 As String = "日付(月日)を入力してください。"
    Public Const GC_ERR_MSG_1123 As String = "発生日を入力してください。"
    Public Const GC_ERR_MSG_1124 As String = "入所予定日を入力してください。"
    Public Const GC_ERR_MSG_1125 As String = "日報日付を入力してください。"
    Public Const GC_ERR_MSG_1126 As String = "発生日付を入力してください。"
    Public Const GC_ERR_MSG_1127 As String = "発生時刻を入力してください。"
    Public Const GC_ERR_MSG_1128 As String = "対象日付を入力してください。"
    Public Const GC_ERR_MSG_1129 As String = "お見舞日を入力してください。"
    Public Const GC_ERR_MSG_1130 As String = "発生日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1131 As String = "発生日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1132 As String = "日報日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1133 As String = "日報日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1134 As String = "時刻（自）を入力してください。"
    Public Const GC_ERR_MSG_1135 As String = "時刻（至）を入力してください。"
    Public Const GC_ERR_MSG_1136 As String = "月数を入力してください。"
    Public Const GC_ERR_MSG_1137 As String = "出力対象日（自）を入力してください。"
    Public Const GC_ERR_MSG_1138 As String = "出力対象日（至）を入力してください。"
    Public Const GC_ERR_MSG_1139 As String = "異動日（自）を入力してください。"
    Public Const GC_ERR_MSG_1140 As String = "異動日（至）を入力してください。"
    Public Const GC_ERR_MSG_1141 As String = "入社年月日を入力してください。"
    Public Const GC_ERR_MSG_1142 As String = "生年月日を入力してください。"
    Public Const GC_ERR_MSG_1143 As String = "免許証交付日を入力してください。"
    Public Const GC_ERR_MSG_1144 As String = "有効期限を入力してください。"
    Public Const GC_ERR_MSG_1145 As String = "売上日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1146 As String = "売上日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1147 As String = "登録日（自）を入力してください。"
    Public Const GC_ERR_MSG_1148 As String = "登録日（至）を入力してください。"
    Public Const GC_ERR_MSG_1149 As String = "入金日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1150 As String = "入金日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1151 As String = "解除日を入力してください。"
    Public Const GC_ERR_MSG_1152 As String = "修正日を入力してください。"
    Public Const GC_ERR_MSG_1153 As String = "台帳日を入力してください。"
    Public Const GC_ERR_MSG_1154 As String = "確定日付を入力してください。"
    Public Const GC_ERR_MSG_1155 As String = "実施日付を入力してください。"
    Public Const GC_ERR_MSG_1156 As String = "締日を入力してください。"
    Public Const GC_ERR_MSG_1157 As String = "免許証年月日を入力してください。"
    Public Const GC_ERR_MSG_1158 As String = "二種合格日を入力してください。"
    Public Const GC_ERR_MSG_1159 As String = "免許証年月日が入力されています。"
    Public Const GC_ERR_MSG_1160 As String = "二種合格日が入力されています。"
    Public Const GC_ERR_MSG_1161 As String = "二種合格日が免許証年月日以後の日付になっています。"
    Public Const GC_ERR_MSG_1162 As String = "請求日を入力してください。"
    Public Const GC_ERR_MSG_1163 As String = "データ引落日を入力してください。"
    Public Const GC_ERR_MSG_1164 As String = "出庫時刻を入力してください。"
    Public Const GC_ERR_MSG_1165 As String = "入庫時刻を入力してください。"
    Public Const GC_ERR_MSG_1166 As String = "ハンドル時間を入力してください。"
    Public Const GC_ERR_MSG_1167 As String = "休憩時間を入力してください。"
    Public Const GC_ERR_MSG_1168 As String = "実休憩時間を入力してください。"
    Public Const GC_ERR_MSG_1169 As String = "深夜時間を入力してください。"
    Public Const GC_ERR_MSG_1170 As String = "2008年03月20日以前の日付は入力できません。"
    Public Const GC_ERR_MSG_1171 As String = "入社月数（自）を入力してください。"
    Public Const GC_ERR_MSG_1172 As String = "入社月数（至）を入力してください。"
    Public Const GC_ERR_MSG_1173 As String = "運用開始日を入力してください。"
    Public Const GC_ERR_MSG_1174 As String = "入所日を入力してください。"
    Public Const GC_ERR_MSG_1175 As String = "卒業日を入力してください。"
    Public Const GC_ERR_MSG_1176 As String = "選任日を入力してください。"
    Public Const GC_ERR_MSG_1177 As String = "伝票日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1178 As String = "伝票日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1179 As String = "支払日を入力してください。"
    Public Const GC_ERR_MSG_1180 As String = "集会日付を入力してください。"
    Public Const GC_ERR_MSG_1181 As String = "廃車日を入力してください。"
    Public Const GC_ERR_MSG_1182 As String = "出力日付（自）を入力してください。"
    Public Const GC_ERR_MSG_1183 As String = "出力日付（至）を入力してください。"
    Public Const GC_ERR_MSG_1184 As String = "出勤時刻を入力してください。"
    Public Const GC_ERR_MSG_1185 As String = "退勤時刻を入力してください。"
    Public Const GC_ERR_MSG_1186 As String = "予定日付を入力してください。"
    Public Const GC_ERR_MSG_1187 As String = "教習期間（自）を入力してください。"
    Public Const GC_ERR_MSG_1188 As String = "教習期間（至）を入力してください。"
    Public Const GC_ERR_MSG_1189 As String = "処理日を入力してください。"
    Public Const GC_ERR_MSG_1190 As String = "処理日（自）を入力してください。"
    Public Const GC_ERR_MSG_1191 As String = "処理日（至）を入力してください。"
    Public Const GC_ERR_MSG_1192 As String = "切替日を入力してください。"
    Public Const GC_ERR_MSG_1193 As String = "切替日（自）を入力してください。"
    Public Const GC_ERR_MSG_1194 As String = "切替日（至）を入力してください。"
    Public Const GC_ERR_MSG_1195 As String = "有効期限（現在）を入力してください。"
    Public Const GC_ERR_MSG_1196 As String = "有効期限（更新後）を入力してください。"
    Public Const GC_ERR_MSG_1197 As String = "請求締日（自）を入力してください。"
    Public Const GC_ERR_MSG_1198 As String = "請求締日（至）を入力してください。"
    Public Const GC_ERR_MSG_1199 As String = "送付日を入力してください。"

    '----------------------------------
    ' 画面項目入力チェック（文字）
    '----------------------------------
    Public Const GC_ERR_MSG_1200 As String = "契約名称を入力してください。"
    Public Const GC_ERR_MSG_1201 As String = "部門名を入力してください。"
    Public Const GC_ERR_MSG_1202 As String = "病院名を入力してください。"
    Public Const GC_ERR_MSG_1203 As String = "保険会社名を入力してください。"
    Public Const GC_ERR_MSG_1204 As String = "種類名を入力してください。"
    Public Const GC_ERR_MSG_1205 As String = "状況名を入力してください。"
    Public Const GC_ERR_MSG_1206 As String = "詳細状況名を入力してください。"
    Public Const GC_ERR_MSG_1207 As String = "市区郡を入力してください。"
    Public Const GC_ERR_MSG_1208 As String = "町村番地を入力してください。"
    Public Const GC_ERR_MSG_1209 As String = "識別を入力してください。"
    Public Const GC_ERR_MSG_1210 As String = "入力ファイルを入力してください。"
    Public Const GC_ERR_MSG_1211 As String = "会員名を入力してください。"
    Public Const GC_ERR_MSG_1212 As String = "窓枠名を入力してください。"
    Public Const GC_ERR_MSG_1213 As String = "従業員名を入力してください。"
    Public Const GC_ERR_MSG_1214 As String = "ファイル名を入力してください。"
    Public Const GC_ERR_MSG_1215 As String = "講義名を入力してください。"
    Public Const GC_ERR_MSG_1216 As String = "内容を入力してください。"
    Public Const GC_ERR_MSG_1217 As String = "地区名を入力してください。"
    Public Const GC_ERR_MSG_1218 As String = "退職理由を入力してください。"
    Public Const GC_ERR_MSG_1219 As String = "指導場所名を入力してください。"
    Public Const GC_ERR_MSG_1220 As String = "指導場所略称を入力してください。"
    Public Const GC_ERR_MSG_1221 As String = "講義略称を入力してください。"
    Public Const GC_ERR_MSG_1222 As String = "フォルダを入力してください。"
    Public Const GC_ERR_MSG_1223 As String = "車種名を入力してください。"

    '----------------------------------
    ' 画面項目入力チェック（数値・金額）
    '----------------------------------
    Public Const GC_ERR_MSG_1300 As String = "契約人数を入力してください。"
    Public Const GC_ERR_MSG_1301 As String = "月額単価を入力してください。"
    Public Const GC_ERR_MSG_1302 As String = "超過単価を入力してください。"
    Public Const GC_ERR_MSG_1303 As String = "深夜単価を入力してください。"
    Public Const GC_ERR_MSG_1304 As String = "売上番号を入力してください。"
    Public Const GC_ERR_MSG_1305 As String = "入金番号を入力してください。"
    Public Const GC_ERR_MSG_1306 As String = "車輌本体価格を入力してください。"
    Public Const GC_ERR_MSG_1307 As String = "取得税を入力してください。"
    Public Const GC_ERR_MSG_1308 As String = "計画番号を入力してください。"
    Public Const GC_ERR_MSG_1309 As String = "受講料を入力してください。"
    Public Const GC_ERR_MSG_1310 As String = "助成率を入力してください。"
    Public Const GC_ERR_MSG_1311 As String = "賃金助成額を入力してください。"
    Public Const GC_ERR_MSG_1312 As String = "事故番号を入力してください。"
    Public Const GC_ERR_MSG_1313 As String = "車輌枝番を入力してください。"
    Public Const GC_ERR_MSG_1314 As String = "チケット番号を入力してください。"
    Public Const GC_ERR_MSG_1315 As String = "チケット番号（自）を入力してください。"
    Public Const GC_ERR_MSG_1316 As String = "チケット番号（至）を入力してください。"
    Public Const GC_ERR_MSG_1317 As String = "受付番号を入力してください。"
    Public Const GC_ERR_MSG_1318 As String = "全走行Kmを入力してください。"
    Public Const GC_ERR_MSG_1319 As String = "規定を入力してください。"
    Public Const GC_ERR_MSG_1320 As String = "新一種手当を入力してください。"
    Public Const GC_ERR_MSG_1321 As String = "旧一種手当を入力してください。"
    Public Const GC_ERR_MSG_1322 As String = "新二種手当を入力してください。"
    Public Const GC_ERR_MSG_1323 As String = "旧二種手当を入力してください。"
    Public Const GC_ERR_MSG_1324 As String = "タクシー協会の養成手当を入力してください。"
    Public Const GC_ERR_MSG_1325 As String = "タクシー協会の教習手当を入力してください。"
    Public Const GC_ERR_MSG_1328 As String = "週番号を入力してください。"
    Public Const GC_ERR_MSG_1329 As String = "登録番号を入力してください。"
    Public Const GC_ERR_MSG_1330 As String = "無線収入を入力してください。"
    Public Const GC_ERR_MSG_1331 As String = "無線回数を入力してください。"
    Public Const GC_ERR_MSG_1332 As String = "ＰＣＳ収入を入力してください。"
    Public Const GC_ERR_MSG_1333 As String = "ＰＣＳ回数を入力してください。"
    Public Const GC_ERR_MSG_1334 As String = "ＳＨ収入を入力してください。"
    Public Const GC_ERR_MSG_1335 As String = "ＳＨ回数を入力してください。"
    Public Const GC_ERR_MSG_1336 As String = "大崎収入を入力してください。"
    Public Const GC_ERR_MSG_1337 As String = "大崎回数を入力してください。"
    Public Const GC_ERR_MSG_1338 As String = "請求番号を入力してください。"

    '----------------------------------
    ' 画面項目選択チェック
    '----------------------------------
    Public Const GC_ERR_MSG_1500 As String = "得意先コードが選択されていません。"
    Public Const GC_ERR_MSG_1501 As String = "契約番号が選択されていません。"
    Public Const GC_ERR_MSG_1502 As String = "従業員コードが選択されていません。"
    Public Const GC_ERR_MSG_1503 As String = "勤怠が選択されていません。"
    Public Const GC_ERR_MSG_1504 As String = "免許の種類が選択されていません。"
    Public Const GC_ERR_MSG_1505 As String = "対象となる行が選択されていません｡"
    Public Const GC_ERR_MSG_1506 As String = "選択された銀行コードと，ファイルの銀行コードが異なります。"
    Public Const GC_ERR_MSG_1507 As String = "表示順が選択されていません。"
    Public Const GC_ERR_MSG_1508 As String = "GPS出力条件が選択されていません。"
    Public Const GC_ERR_MSG_1509 As String = "顔写真が選択されていません。"
    Public Const GC_ERR_MSG_1510 As String = "指導監督項目が選択されていません。"
    Public Const GC_ERR_MSG_1511 As String = "表示対象が選択されていません。"
    Public Const GC_ERR_MSG_1512 As String = "印刷対象が選択されていません。"
    Public Const GC_ERR_MSG_1513 As String = "削除対象が選択されていません。"
    Public Const GC_ERR_MSG_1514 As String = "新規ファイルの対象がありません。"

    '----------------------------------
    ' 設定チェック
    '----------------------------------
    Public Const GC_ERR_MSG_3000 As String = "契約マスタに時間単価が設定されていません。"
    Public Const GC_ERR_MSG_3001 As String = "契約マスタに休日時間単価が設定されていません。"
    Public Const GC_ERR_MSG_3002 As String = "契約マスタに深夜単価が設定されていません。"
    Public Const GC_ERR_MSG_3003 As String = "契約マスタに休日深夜単価が設定されていません。"
    Public Const GC_ERR_MSG_3004 As String = "得意先マスタに立替手数料率が設定されていません。"
    Public Const GC_ERR_MSG_3005 As String = "契約マスタの契約終了日を過ぎています。"
    Public Const GC_ERR_MSG_3006 As String = "手数料が設定されているため変更できません。"
    Public Const GC_ERR_MSG_3007 As String = "不良債権先のため変更できません。"
    Public Const GC_ERR_MSG_3008 As String = "手数料率が異なるため変更できません。"
    Public Const GC_ERR_MSG_3009 As String = "請求済み旅行会社のため変更できません。"
    Public Const GC_ERR_MSG_3010 As String = "従業員マスタのファーストが乗務員です。"
    Public Const GC_ERR_MSG_3011 As String = "ＭＫ会員マスタで, 枝コード 0000 が入力できないように設定されています。"
    Public Const GC_ERR_MSG_3012 As String = "ＭＫ会員マスタで，枝コード 0000 しか入力できないように設定されています。"
    Public Const GC_ERR_MSG_3013 As String = "照会モードの為, 削除できません。"
    Public Const GC_ERR_MSG_3014 As String = "照会モードの為, 登録できません。"
    Public Const GC_ERR_MSG_3015 As String = "請求データが存在する為, 削除できません。"
    Public Const GC_ERR_MSG_3016 As String = "従業員マスタのランクが不足している為, 再発行できません。"
    Public Const GC_ERR_MSG_3017 As String = "名称マスタに識別='整備参照先'が設定されていません。"

    '----------------------------------
    ' 数値チェック
    '----------------------------------
    Public Const GC_ERR_MSG_4000 As String = "ハンドル時間に負の値が入力されています。"
    Public Const GC_ERR_MSG_4001 As String = "総収に負の値が入力されています。"
    Public Const GC_ERR_MSG_4002 As String = "乗車金額以上の金額が入力されています。"
    Public Const GC_ERR_MSG_4003 As String = "乗務員金額に０円以下の値が入力されています。"
    Public Const GC_ERR_MSG_4004 As String = "乗車人数以上の割引があります。"
    Public Const GC_ERR_MSG_4005 As String = "割引単価で割り切れません。"
    Public Const GC_ERR_MSG_4006 As String = "深夜時間に負の値が入力されています。"
    Public Const GC_ERR_MSG_4007 As String = "深夜時間に７ｈを超える値が入力されています。"

    '----------------------------------
    ' 相関チェック
    '----------------------------------
    Public Const GC_ERR_MSG_5000 As String = "ハンドル時間が0時間で売上があります。"
    Public Const GC_ERR_MSG_5001 As String = "休みの勤怠区分で売上があります。"
    Public Const GC_ERR_MSG_5002 As String = "車輌区分が未入力で売上があります。"
    Public Const GC_ERR_MSG_5003 As String = "未収区分が21の場合，手数料率が0%の会員は入力できません。"
    Public Const GC_ERR_MSG_5004 As String = "出庫時刻は入庫時刻より小さい値を入力して下さい。"
    Public Const GC_ERR_MSG_5005 As String = "出勤時刻は退勤時刻より小さい値を入力して下さい。"
    Public Const GC_ERR_MSG_5006 As String = "入庫時刻は出庫時刻より大きい値を入力して下さい。"
    Public Const GC_ERR_MSG_5007 As String = "退勤時刻は出勤時刻より大きい値を入力して下さい。"
    Public Const GC_ERR_MSG_5008 As String = "控除走行Kmが全走行Kmを越えています。"
    Public Const GC_ERR_MSG_5009 As String = "乗務員金額が乗車単価未満です。"
    Public Const GC_ERR_MSG_5010 As String = "その後金額がその後単価で割切れません。"
    Public Const GC_ERR_MSG_5011 As String = "日報での入力より英会話ガイドが大きくなっています。"
    Public Const GC_ERR_MSG_5012 As String = "確定された入金日は入力できません。"
    Public Const GC_ERR_MSG_5013 As String = "確定された営業日は入力できません。"
    Public Const GC_ERR_MSG_5014 As String = "マスタの締日と入力された締日が異なります。"
    Public Const GC_ERR_MSG_5015 As String = "乗務員金額と貸切単価で除算した剰余が０以外になっています。"
    Public Const GC_ERR_MSG_5016 As String = "乗車金額以上の金額が入力されています。"
    Public Const GC_ERR_MSG_5017 As String = "未収明細の英ガイドが営業日報の英ガイドより大きくなっています。"
    Public Const GC_ERR_MSG_5018 As String = "未収区分が22の場合，手数料率が0%の会員は入力できません。"
    Public Const GC_ERR_MSG_5019 As String = "貸切明細から作成された未収明細は削除できません。"
    Public Const GC_ERR_MSG_5020 As String = "チケット発行時の会員コードと異なります。"
    Public Const GC_ERR_MSG_5021 As String = "請求集計処理中の為，請求締日は変更できません。"
    Public Const GC_ERR_MSG_5022 As String = "教習センターに入所していない従業員です。"
    Public Const GC_ERR_MSG_5023 As String = "教習センターを卒業されている従業員です。"
    Public Const GC_ERR_MSG_5024 As String = "教習センター入所日が出席日付以降の為, 入力できません。"
    Public Const GC_ERR_MSG_5025 As String = "既に卒業されている為。入所取消できません。"
    Public Const GC_ERR_MSG_5026 As String = "既に選任されている為。入所取消できません。"
    Public Const GC_ERR_MSG_5027 As String = "既に卒業されている為。選任取消できません。"
    Public Const GC_ERR_MSG_5028 As String = "月次範囲内の日付を入力してください。"
    Public Const GC_ERR_MSG_5029 As String = "有給残日数が不足している為, 入力できません。"
    Public Const GC_ERR_MSG_5030 As String = "入社前の日付は処理できません。"
    Public Const GC_ERR_MSG_5031 As String = "退社後の日付は処理できません。"
    Public Const GC_ERR_MSG_5032 As String = "公休日以外は公出予約できません。"
    Public Const GC_ERR_MSG_5033 As String = "深夜時間がハンドル時間を越えています。"
    Public Const GC_ERR_MSG_5034 As String = "実動予定日が卒業年月日より以前の日付です。"
    Public Const GC_ERR_MSG_5035 As String = "チケット発行時の会員コードと異なります。"

    '----------------------------------
    ' 複数行エラーメッセージ
    '----------------------------------
    Public Const GC_ERR_MSG_8000 As String = "従業員ｺｰﾄﾞとﾊﾟｽﾜｰﾄﾞを確認して，" & vbCrLf & "もう一度入力して下さい。"
    Public Const GC_ERR_MSG_8001 As String = "該当する振込先データが，口座番号マスタに存在しませんでした。" & vbCrLf & "口座番号マスタへの登録を行ってください。"
    Public Const GC_ERR_MSG_8002 As String = "出向先が休日です。" & vbCrLf & "出勤入力できません。"
    Public Const GC_ERR_MSG_8003 As String = "業務日報入力（管理先）では行削除できません。" & vbCrLf & "業務日報入力から削除してください。"
    Public Const GC_ERR_MSG_8004 As String = "入金データが存在するため削除できません。" & vbCrLf & "入金入力画面で入金データの削除を行って下さい。"
    Public Const GC_ERR_MSG_8005 As String = "楽々道中と連動されている入金データは削除できません。" & vbCrLf & "楽々道中で入金データの取消を行ってください。"
    Public Const GC_ERR_MSG_8006 As String = "他のﾕｰｻﾞｰが同じｺｰﾄﾞを変更している為、" & vbCrLf & "処理の続行は出来ません。"
    Public Const GC_ERR_MSG_8007 As String = "請求データが存在しない為, " & vbCrLf & "自動振替データが作成できません。"
    Public Const GC_ERR_MSG_8008 As String = "データ引落日が請求締日より前です。" & vbCrLf & "修正してください。"
    Public Const GC_ERR_MSG_8009 As String = "総収が10,000以上かつハンドル時間が5時間以上で" & vbCrLf & "勤怠が特別早退または特別早退公出です。"
    Public Const GC_ERR_MSG_8010 As String = "労働時間が8時間以上で" & vbCrLf & "勤怠が早退または公休出勤早退です。"
    Public Const GC_ERR_MSG_8011 As String = "拘束時間が9時間以上で" & vbCrLf & "勤怠が早退または公休出勤早退です。"
    Public Const GC_ERR_MSG_8012 As String = "労働時間が8時間以上で" & vbCrLf & "勤怠が中断または公休出勤中断です。"

    '----------------------------------
    ' 共通エラーメッセージ
    '----------------------------------
    Public Const GC_ERR_MSG_9000 As String = "不正な値が入力されました。"
    Public Const GC_ERR_MSG_9001 As String = "指定した範囲が不正です。"
    Public Const GC_ERR_MSG_9002 As String = "該当するデータがありません。"
    Public Const GC_ERR_MSG_9003 As String = "数値以外入力できません。"
    Public Const GC_ERR_MSG_9004 As String = "1以上かつ31以下の数値を入力してください。"
    Public Const GC_ERR_MSG_9005 As String = "明細が入力されていません。"
    Public Const GC_ERR_MSG_9006 As String = "この行は削除できません。"
    Public Const GC_ERR_MSG_9007 As String = "システム日付未満で入力してください。"
    Public Const GC_ERR_MSG_9008 As String = "システム日付以下で入力してください。"
    Public Const GC_ERR_MSG_9009 As String = "対象データがありません。"
    Public Const GC_ERR_MSG_9010 As String = "権限がありません。"
    Public Const GC_ERR_MSG_9011 As String = "A ～ Zの間で入力してください。"
    Public Const GC_ERR_MSG_9012 As String = "マイナスは入力できません。"
    Public Const GC_ERR_MSG_9013 As String = "00：00 ～ 11：59の間で入力してください。"
    Public Const GC_ERR_MSG_9014 As String = "ファイルが見つかりません。"
    Public Const GC_ERR_MSG_9015 As String = "入力された書式が不正です。"
    Public Const GC_ERR_MSG_9016 As String = "1 ～ 12の間で入力してください。"
    Public Const GC_ERR_MSG_9017 As String = "空き容量が足りません。"
    Public Const GC_ERR_MSG_9018 As String = "1,000で割り切れない数値が入力されました。"
    Public Const GC_ERR_MSG_9019 As String = "明細が変更されていません。"
    Public Const GC_ERR_MSG_9020 As String = "負の値は入力できません。"
    Public Const GC_ERR_MSG_9021 As String = "60分を超えています。"
    Public Const GC_ERR_MSG_9022 As String = "2桁で入力してください。"
    Public Const GC_ERR_MSG_9023 As String = "キー項目が重複しています。"
    Public Const GC_ERR_MSG_9024 As String = "月数に誤りがあります。"
    Public Const GC_ERR_MSG_9025 As String = "新規登録の権限がありません。"
    Public Const GC_ERR_MSG_9026 As String = "ファイルの出力に失敗しました。"
    Public Const GC_ERR_MSG_9027 As String = "16桁で入力してください。"
    Public Const GC_ERR_MSG_9028 As String = "整数4桁以内で入力してください。"
    Public Const GC_ERR_MSG_9029 As String = "時刻には時刻(時：分)を入力して下さい。"
    Public Const GC_ERR_MSG_9030 As String = "明細に空きがありません。"
    Public Const GC_ERR_MSG_9031 As String = "フォルダが存在しません。"
    Public Const GC_ERR_MSG_9032 As String = "社員以外は入力できません。"
    Public Const GC_ERR_MSG_9033 As String = "データが変更されていません。"
    Public Const GC_ERR_MSG_9034 As String = "会員コードが不正です。"
    Public Const GC_ERR_MSG_9035 As String = "10円単位で入力してください。"
    Public Const GC_ERR_MSG_9036 As String = "データが変更されています。"
    Public Const GC_ERR_MSG_9037 As String = "対象ファイルがありません。"
    Public Const GC_ERR_MSG_9038 As String = "ファイルは全て処理済みです。"
    Public Const GC_ERR_MSG_9039 As String = "合計金額が一致しません。"
    Public Const GC_ERR_MSG_9040 As String = "会員コード、従業員コード、無線番号　いずれかを入力してください。"

    '==============================================================================
    ' 確認メッセージ
    '==============================================================================
    Public Const GC_QST_MSG_0001 As String = "削除処理します。よろしいですか？"
    Public Const GC_QST_MSG_0002 As String = "入力した社員は、二種免許を取得していませんが教習入所ですか？"
    Public Const GC_QST_MSG_0003 As String = "入力した社員は、二種免許を取得していますが養成入所ですか？"
    Public Const GC_QST_MSG_0004 As String = "月度の承認を取り消しますか？" & vbCrLf & "承認取消を行った場合, 再度, 職員シフト入力から行う必要が有ります。"
    Public Const GC_QST_MSG_0005 As String = "所属部署以外の部署の承認を行いますか？"
    Public Const GC_QST_MSG_0006 As String = "月度の勤怠データを作成します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0007 As String = "得意先コードがマスタに存在しません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0008 As String = "発生日が入力されていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0009 As String = "請求書を印刷しますか？"
    Public Const GC_QST_MSG_0010 As String = "請求書(控え)を印刷しますか？"
    Public Const GC_QST_MSG_0011 As String = "登録されている得意先情報を反映します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0012 As String = "売上データを作成します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0013 As String = "売掛残高を計算します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0014 As String = "月度の給与データを作成します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0015 As String = "運管勤怠テーブルの手当金額を再計算します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0016 As String = "手数料率が０％です。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0017 As String = "楽々道中と連携されている得意先コードですが" & vbCrLf & "売上データが連携されていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0018 As String = "郵便料金マスタの内容をチケット還付データに反映します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0019 As String = "既にチケット番号がセットされています。" & vbCrLf & "再実行しますか？"
    Public Const GC_QST_MSG_0020 As String = "確定します。よろしいですか？"
    Public Const GC_QST_MSG_0021 As String = "確定解除します。よろしいですか？"
    Public Const GC_QST_MSG_0022 As String = "既にチケット還付データが作成されています。" & vbCrLf & "現在のチケット還付データは削除されますが，よろしいですか？"
    Public Const GC_QST_MSG_0023 As String = "既に処理済です。" & vbCrLf & "再実行してもよろしいですか？"
    Public Const GC_QST_MSG_0024 As String = "日付が入力されていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0025 As String = "請求済みです。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0026 As String = "手数料合計より請求する手数料が多くなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0027 As String = "自動振替データを抽出します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0028 As String = "自動振替データがすでに作成されています。" & vbCrLf & "再作成しますか？"
    Public Const GC_QST_MSG_0029 As String = "ＣＳＶファイルに出力します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0030 As String = "ＣＳＶファイルから取り込みます。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0031 As String = "1,000で割り切れない数値が入力されています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0032 As String = "締日が異なります。更新してもよろしいですか？"
    Public Const GC_QST_MSG_0033 As String = "随時請求の会員ではありません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0034 As String = "登録処理します。よろしいですか？"
    Public Const GC_QST_MSG_0035 As String = "窓枠名に反映します。よろしいですか？"
    Public Const GC_QST_MSG_0036 As String = "チケット表示名に反映します。よろしいですか？"
    Public Const GC_QST_MSG_0037 As String = "事務手数料をクリアします。よろしいですか？"
    Public Const GC_QST_MSG_0038 As String = "事務手数料率をクリアします。よろしいですか？"
    Public Const GC_QST_MSG_0039 As String = "請求締日が２０になっていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0040 As String = "請求済みです。" & vbCrLf & "修正してよろしいですか？"
    Public Const GC_QST_MSG_0041 As String = "ファーストが異なります。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0042 As String = "大型ハイヤーに乗務しています。" & vbCrLf & "売上率計算をして下さい。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0043 As String = "乗務員がハイヤーまたはジャンボに乗務しています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0044 As String = "遅刻, 早退, 中断の勤怠を確認してください。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0045 As String = "全走行Kmが乗車走行Kmより小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0046 As String = "税込運収および高速プレートが０円で，" & vbCrLf & "未収明細が入力されています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0047 As String = "ハンドル時間が拘束時間より大きくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0048 As String = "拘束時間が4時間未満になります。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0049 As String = "出庫時刻が07:00より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0050 As String = "全走行Km(入庫)が全走行Km(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0051 As String = "乗車Km(入庫)が乗車Km(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0052 As String = "乗車回数(入庫)が乗車回数(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0053 As String = "その後回数(入庫)がその後回数(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0054 As String = "迎車回数(入庫)が迎車回数(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0055 As String = "身障割引(入庫)が身障割引(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0056 As String = "敬割指数(入庫)が敬割指数(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0057 As String = "遠割指数(入庫)が遠割指数(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0058 As String = "他部署の従業員が入力されています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0059 As String = "メータで手数料率0％にします。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0060 As String = "車輌走行Km(入庫)が車輌走行Km(出庫)より小さくなっています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0061 As String = "36時を超えています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0062 As String = "乗り換えになります。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0063 As String = "勤次郎部門コードが変更されていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0064 As String = "規定公休日数を超えています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0065 As String = "有給残日数が不足しています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0066 As String = "規定公休日数が不足しています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0067 As String = "入力されたシャトル明細が削除されます。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0068 As String = "シャトル明細が入力されていません。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0069 As String = "休務日報データが既に存在します。" & vbCrLf & "データを再作成しますか？"
    Public Const GC_QST_MSG_0070 As String = "休務日報データが既に存在します。" & vbCrLf & "データを確定しますか？"
    Public Const GC_QST_MSG_0071 As String = "営業車輌マスタ・その他費用（新車装備）を更新します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0072 As String = "未収明細と関連のある貸切明細が変更されました。" & vbCrLf & "この情報を関連する未収明細に反映しますか？" & vbCrLf & "(キャンセルを押下すると未収明細には反映されません。)"
    Public Const GC_QST_MSG_0073 As String = "入力されたシャトル明細が削除されます。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0074 As String = "タクシー車輌で未収区分に21が入力されています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0075 As String = "行目を削除処理します。よろしいですか？"
    Public Const GC_QST_MSG_0076 As String = "ＰＯＳ明細の空車走行時間が最大値を超えている可能性があります。" & vbCrLf & "ハンドル時間を確認してください。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0077 As String = "社員貸付データ自動作成処理は正常に終了しました。" & vbCrLf & "貸付入力画面に遷移しますか？"
    Public Const GC_QST_MSG_0078 As String = "社員貸付データ自動作成処理は正常に終了しました。" & vbCrLf & "貸付一覧表画面に遷移しますか？"
    Public Const GC_QST_MSG_0079 As String = "貸付免除入金データ作成処理は正常に終了しました。" & vbCrLf & "貸付入金一覧表画面に遷移しますか？"
    Public Const GC_QST_MSG_0080 As String = "指定したフォルダが存在しません。" & vbCrLf & "登録しますか？"
    Public Const GC_QST_MSG_0081 As String = "システム日付より後の日付です。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0082 As String = "教習データより日報データを作成します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0083 As String = "講義を変更します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0084 As String = "講義を取消します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0085 As String = "月間スケジュールデータが存在しません。" & vbCrLf & "週間スケジュールデータより月間スケジュールデータを作成しますか？"
    Public Const GC_QST_MSG_0086 As String = "予約を取消します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0087 As String = "予約を登録します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0088 As String = "取消処理します。よろしいですか？"
    Public Const GC_QST_MSG_0089 As String = "既に出席で登録されています。" & vbCrLf & "出席取消を行います。よろしいですか？"
    Public Const GC_QST_MSG_0090 As String = "予定シフトを変更します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0091 As String = "エラーが発生しています。" & vbCrLf & "エラーログファイルを表示しますか？"
    Public Const GC_QST_MSG_0092 As String = "ＳＨ回数が１０回を超えています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0093 As String = "行を削除します。よろしいですか？"
    Public Const GC_QST_MSG_0094 As String = "輸送実績データを登録します" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0095 As String = "処理日から算出した月度範囲外の日付が入力されています。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0096 As String = "ファイルに出力します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0097 As String = "ファイルを取込みます。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0098 As String = "振替結果より入金データを作成します。" & vbCrLf & "よろしいですか？"
    Public Const GC_QST_MSG_0099 As String = "検索条件が入力されていません。" & vbCrLf & "よろしいですか？"

    Public Const GC_QST_MSG_0500 As String = "請求締日が変更されています。" & vbCrLf & "得意先マスタの請求締日を反映しますか？"
    Public Const GC_QST_MSG_0501 As String = "回収サイクルが変更されています。" & vbCrLf & "得意先マスタの回収サイクルを反映しますか？"
    Public Const GC_QST_MSG_0502 As String = "回収日が変更されています。" & vbCrLf & "得意先マスタの回収日を反映しますか？"
    Public Const GC_QST_MSG_0503 As String = "税通知が変更されています。" & vbCrLf & "得意先マスタの税通知を反映しますか？"
    Public Const GC_QST_MSG_0504 As String = "税端数が変更されています。" & vbCrLf & "得意先マスタの税端数を反映しますか？"
    Public Const GC_QST_MSG_0505 As String = "手数料率が変更されています。" & vbCrLf & "得意先マスタの手数料率を反映しますか？"
    Public Const GC_QST_MSG_0506 As String = "楽々道中と得意先マスタの手数料率が異なります。" & vbCrLf & "得意先マスタの手数料率を反映しますか？"
    Public Const GC_QST_MSG_0507 As String = "立替手数料率が変更されています。" & vbCrLf & "得意先マスタの立替手数料率を反映しますか？"
    Public Const GC_QST_MSG_0508 As String = "楽々道中と得意先マスタの立替手数料率が異なります。" & vbCrLf & "得意先マスタの立替手数料率を反映しますか？"
    Public Const GC_QST_MSG_0509 As String = "様御中区分が変更されています。" & vbCrLf & "得意先マスタの様御中区分を反映しますか？"
    Public Const GC_QST_MSG_0510 As String = "請求会社コードが変更されています。" & vbCrLf & "得意先マスタの請求会社コードを反映しますか？"
    Public Const GC_QST_MSG_0511 As String = "扱業者コードが変更されています。" & vbCrLf & "得意先マスタの扱業者コードを反映しますか？"
    Public Const GC_QST_MSG_0512 As String = "得意先マスタが登録されていません。" & vbCrLf & "扱業者マスタの情報を得意先マスタに登録しますか？"
    Public Const GC_QST_MSG_0513 As String = "請求所属コードが変更されています。" & vbCrLf & "得意先マスタの請求所属コードを反映しますか？"
    Public Const GC_QST_MSG_0514 As String = "パーフェクト番号が変更されています。" & vbCrLf & "得意先マスタのパーフェクト番号を反映しますか？"
    Public Const GC_QST_MSG_0515 As String = "振込先口座が変更されています。" & vbCrLf & "得意先マスタの振込先口座を反映しますか？"
End Module